{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "httpbin.fullname" . }}
  namespace: {{ template "httpbin.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "httpbin.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicaCount }}
  maxReplicas: {{ .Values.hpa.maxReplicaCount }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
{{- end }}
