---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ argocd_github_secret_name }}"
  namespace: "{{ argocd_namespace }}"
  labels:
    managed-by: ansible
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: https://github.com/paulden/
  username: "{{ argocd_github_token_user }}"
  password: "{{ argocd_github_token_password }}"
