global:
  revision: master
  dns: toto.com
  registry:
    gcr: "gcr.io"
  repositories:
    argocd: 'https://argoproj.github.io/argo-helm'
    nginx: 'https://kubernetes.github.io/ingress-nginx'
    cert_manager: 'https://charts.jetstack.io'

argocd:
  namespace: argocd

ingress:
  namespace: ingress-nginx
  service:
    type: ClusterIP

cert_manager:
  namespace: cert-manager
