apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app: cert-manager-cluster-issuer-prod
    deployed_by: argocd
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: nologin@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
