apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app: cert-manager-cluster-issuer-staging
    deployed_by: argocd
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: nologin@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx
