apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.cert_manager.cluster_issuer_staging }}
  labels:
    app: cert-manager-cluster-issuer-staging
    deployed_by: argocd
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: nologin@gmail.com
    privateKeySecretRef:
      name: {{ .Values.cert_manager.cluster_issuer_staging }}
    solvers:
      - http01:
          ingress:
            class: nginx
